/**
 * Seed ~100 well-known companies per industry (10 industries = ~1000 total).
 * Idempotent: upserts by (userId, name).
 *
 * Run: npx ts-node src/scripts/seed-companies.ts
 * Env: OWNER_TELEGRAM_ID (optional) or uses first user in DB
 */

import dotenv from "dotenv";
dotenv.config();

import { prisma } from "../db/client";

interface CompanySeed {
  name: string;
  careersUrl: string;
  atsType: string;
  atsToken?: string;
  industry: string;
  continent: string;
  remoteFriendly: boolean;
}

function detectATS(url: string): { atsType: string; atsToken: string | null } {
  if (url.includes("greenhouse.io")) {
    const m = url.match(/greenhouse\.io\/([^/?#]+)/);
    return { atsType: "greenhouse", atsToken: m?.[1] ?? null };
  }
  if (url.includes("lever.co")) {
    const m = url.match(/lever\.co\/([^/?#]+)/);
    return { atsType: "lever", atsToken: m?.[1] ?? null };
  }
  if (url.includes("workable.com")) {
    const m = url.match(/workable\.com\/([^/?#]+)/);
    return { atsType: "workable", atsToken: m?.[1] ?? null };
  }
  if (url.includes("ashbyhq.com")) {
    const m = url.match(/ashbyhq\.com\/([^/?#]+)/);
    return { atsType: "ashby", atsToken: m?.[1] ?? null };
  }
  return { atsType: "careers_page", atsToken: null };
}

const COMPANIES: Omit<CompanySeed, "atsType" | "atsToken">[] = [
  // ─── Fintech ──────────────────────────────────────────────────────────────
  { name: "Stripe",         careersUrl: "https://stripe.com/jobs",                           industry: "Fintech",       continent: "North America", remoteFriendly: true  },
  { name: "Plaid",          careersUrl: "https://plaid.com/careers",                         industry: "Fintech",       continent: "North America", remoteFriendly: true  },
  { name: "Robinhood",      careersUrl: "https://careers.robinhood.com",                     industry: "Fintech",       continent: "North America", remoteFriendly: true  },
  { name: "Chime",          careersUrl: "https://www.chime.com/careers",                     industry: "Fintech",       continent: "North America", remoteFriendly: true  },
  { name: "Square",         careersUrl: "https://careers.squareup.com",                      industry: "Fintech",       continent: "North America", remoteFriendly: true  },
  { name: "Brex",           careersUrl: "https://www.brex.com/careers",                      industry: "Fintech",       continent: "North America", remoteFriendly: true  },
  { name: "Affirm",         careersUrl: "https://www.affirm.com/careers",                    industry: "Fintech",       continent: "North America", remoteFriendly: true  },
  { name: "Klarna",         careersUrl: "https://www.klarna.com/careers",                    industry: "Fintech",       continent: "Europe",        remoteFriendly: true  },
  { name: "Revolut",        careersUrl: "https://www.revolut.com/careers",                   industry: "Fintech",       continent: "Europe",        remoteFriendly: false },
  { name: "Monzo",          careersUrl: "https://monzo.com/careers",                         industry: "Fintech",       continent: "Europe",        remoteFriendly: true  },
  { name: "Starling Bank",  careersUrl: "https://www.starlingbank.com/careers",               industry: "Fintech",       continent: "Europe",        remoteFriendly: false },
  { name: "N26",            careersUrl: "https://n26.com/en/careers",                        industry: "Fintech",       continent: "Europe",        remoteFriendly: false },
  { name: "Wise",           careersUrl: "https://www.wise.jobs",                             industry: "Fintech",       continent: "Europe",        remoteFriendly: true  },
  { name: "SumUp",          careersUrl: "https://www.sumup.com/careers",                     industry: "Fintech",       continent: "Europe",        remoteFriendly: false },
  { name: "Checkout.com",   careersUrl: "https://www.checkout.com/careers",                  industry: "Fintech",       continent: "Europe",        remoteFriendly: false },
  { name: "Nubank",         careersUrl: "https://nubank.com.br/en/careers",                  industry: "Fintech",       continent: "Latin America", remoteFriendly: true  },
  { name: "Adyen",          careersUrl: "https://www.adyen.com/careers",                     industry: "Fintech",       continent: "Europe",        remoteFriendly: false },
  { name: "Marqeta",        careersUrl: "https://www.marqeta.com/company/careers",           industry: "Fintech",       continent: "North America", remoteFriendly: true  },
  { name: "Paysafe",        careersUrl: "https://www.paysafe.com/careers",                   industry: "Fintech",       continent: "Europe",        remoteFriendly: false },
  { name: "Payoneer",       careersUrl: "https://www.payoneer.com/careers",                  industry: "Fintech",       continent: "North America", remoteFriendly: true  },
  { name: "Dave",           careersUrl: "https://dave.com/careers",                          industry: "Fintech",       continent: "North America", remoteFriendly: true  },
  { name: "Current",        careersUrl: "https://current.com/careers",                       industry: "Fintech",       continent: "North America", remoteFriendly: true  },
  { name: "Varo Bank",      careersUrl: "https://www.varomoney.com/careers",                 industry: "Fintech",       continent: "North America", remoteFriendly: false },
  { name: "Mercury",        careersUrl: "https://mercury.com/jobs",                          industry: "Fintech",       continent: "North America", remoteFriendly: true  },
  { name: "Ramp",           careersUrl: "https://ramp.com/careers",                          industry: "Fintech",       continent: "North America", remoteFriendly: true  },
  { name: "Pleo",           careersUrl: "https://www.pleo.io/en/careers",                    industry: "Fintech",       continent: "Europe",        remoteFriendly: true  },
  { name: "Spendesk",       careersUrl: "https://www.spendesk.com/careers",                  industry: "Fintech",       continent: "Europe",        remoteFriendly: true  },
  { name: "Payhawk",        careersUrl: "https://payhawk.com/careers",                       industry: "Fintech",       continent: "Europe",        remoteFriendly: false },
  { name: "TrueLayer",      careersUrl: "https://truelayer.com/careers",                     industry: "Fintech",       continent: "Europe",        remoteFriendly: true  },
  { name: "GoCardless",     careersUrl: "https://gocardless.com/about/careers",              industry: "Fintech",       continent: "Europe",        remoteFriendly: true  },
  { name: "Yapily",         careersUrl: "https://www.yapily.com/careers",                    industry: "Fintech",       continent: "Europe",        remoteFriendly: true  },
  { name: "Zopa",           careersUrl: "https://www.zopa.com/careers",                      industry: "Fintech",       continent: "Europe",        remoteFriendly: false },
  { name: "OakNorth",       careersUrl: "https://www.oaknorth.com/careers",                  industry: "Fintech",       continent: "Europe",        remoteFriendly: false },
  { name: "Railsr",         careersUrl: "https://www.railsr.com/careers",                    industry: "Fintech",       continent: "Europe",        remoteFriendly: true  },
  { name: "Thought Machine", careersUrl: "https://thoughtmachine.net/careers",               industry: "Fintech",       continent: "Europe",        remoteFriendly: false },
  { name: "Mambu",          careersUrl: "https://www.mambu.com/careers",                     industry: "Fintech",       continent: "Europe",        remoteFriendly: true  },
  { name: "Nuvei",          careersUrl: "https://www.nuvei.com/careers",                     industry: "Fintech",       continent: "North America", remoteFriendly: false },
  { name: "Bolt Financial", careersUrl: "https://www.bolt.com/careers",                      industry: "Fintech",       continent: "North America", remoteFriendly: true  },
  { name: "Plastiq",        careersUrl: "https://www.plastiq.com/about/careers",             industry: "Fintech",       continent: "North America", remoteFriendly: true  },
  { name: "Tipalti",        careersUrl: "https://tipalti.com/careers",                       industry: "Fintech",       continent: "North America", remoteFriendly: false },
  { name: "Bill.com",       careersUrl: "https://www.bill.com/company/careers",              industry: "Fintech",       continent: "North America", remoteFriendly: true  },
  { name: "Pipe",           careersUrl: "https://pipe.com/careers",                          industry: "Fintech",       continent: "North America", remoteFriendly: true  },
  { name: "Clearco",        careersUrl: "https://clearco.com/careers",                       industry: "Fintech",       continent: "North America", remoteFriendly: true  },
  { name: "Capchase",       careersUrl: "https://www.capchase.com/careers",                  industry: "Fintech",       continent: "Europe",        remoteFriendly: true  },
  { name: "Parafin",        careersUrl: "https://parafin.com/careers",                       industry: "Fintech",       continent: "North America", remoteFriendly: true  },
  { name: "Melio",          careersUrl: "https://meliopayments.com/careers",                 industry: "Fintech",       continent: "North America", remoteFriendly: false },
  { name: "Paystand",       careersUrl: "https://www.paystand.com/careers",                  industry: "Fintech",       continent: "North America", remoteFriendly: true  },
  { name: "Telda",          careersUrl: "https://telda.app/careers",                         industry: "Fintech",       continent: "Africa",        remoteFriendly: false },
  { name: "Flutterwave",    careersUrl: "https://flutterwave.com/us/careers",                industry: "Fintech",       continent: "Africa",        remoteFriendly: false },
  { name: "Wave",           careersUrl: "https://www.wave.com/en/careers",                   industry: "Fintech",       continent: "Africa",        remoteFriendly: false },

  // ─── SaaS ─────────────────────────────────────────────────────────────────
  { name: "Notion",         careersUrl: "https://boards.greenhouse.io/notion",               industry: "SaaS",          continent: "North America", remoteFriendly: true  },
  { name: "Figma",          careersUrl: "https://boards.greenhouse.io/figma",                industry: "SaaS",          continent: "North America", remoteFriendly: true  },
  { name: "Loom",           careersUrl: "https://www.loom.com/careers",                      industry: "SaaS",          continent: "North America", remoteFriendly: true  },
  { name: "Airtable",       careersUrl: "https://boards.greenhouse.io/airtable",             industry: "SaaS",          continent: "North America", remoteFriendly: true  },
  { name: "Miro",           careersUrl: "https://miro.com/careers",                          industry: "SaaS",          continent: "Europe",        remoteFriendly: true  },
  { name: "Linear",         careersUrl: "https://linear.app/careers",                        industry: "SaaS",          continent: "North America", remoteFriendly: true  },
  { name: "Retool",         careersUrl: "https://retool.com/careers",                        industry: "SaaS",          continent: "North America", remoteFriendly: false },
  { name: "Zapier",         careersUrl: "https://zapier.com/jobs",                           industry: "SaaS",          continent: "North America", remoteFriendly: true  },
  { name: "monday.com",     careersUrl: "https://monday.com/jobs",                           industry: "SaaS",          continent: "Europe",        remoteFriendly: false },
  { name: "Asana",          careersUrl: "https://asana.com/jobs",                            industry: "SaaS",          continent: "North America", remoteFriendly: true  },
  { name: "HubSpot",        careersUrl: "https://www.hubspot.com/jobs",                      industry: "SaaS",          continent: "North America", remoteFriendly: true  },
  { name: "Salesforce",     careersUrl: "https://salesforce.wd12.myworkdayjobs.com/External", industry: "SaaS",         continent: "North America", remoteFriendly: true  },
  { name: "Zendesk",        careersUrl: "https://jobs.zendesk.com",                          industry: "SaaS",          continent: "North America", remoteFriendly: true  },
  { name: "Intercom",       careersUrl: "https://www.intercom.com/careers",                  industry: "SaaS",          continent: "Europe",        remoteFriendly: true  },
  { name: "Drift",          careersUrl: "https://www.drift.com/careers",                     industry: "SaaS",          continent: "North America", remoteFriendly: true  },
  { name: "Pendo",          careersUrl: "https://www.pendo.io/careers",                      industry: "SaaS",          continent: "North America", remoteFriendly: true  },
  { name: "Mixpanel",       careersUrl: "https://mixpanel.com/jobs",                         industry: "SaaS",          continent: "North America", remoteFriendly: true  },
  { name: "Amplitude",      careersUrl: "https://amplitude.com/careers",                     industry: "SaaS",          continent: "North America", remoteFriendly: true  },
  { name: "Segment",        careersUrl: "https://www.twilio.com/en-us/company/jobs",         industry: "SaaS",          continent: "North America", remoteFriendly: true  },
  { name: "Heap",           careersUrl: "https://heap.io/careers",                           industry: "SaaS",          continent: "North America", remoteFriendly: true  },
  { name: "FullStory",      careersUrl: "https://www.fullstory.com/careers",                 industry: "SaaS",          continent: "North America", remoteFriendly: true  },
  { name: "Hotjar",         careersUrl: "https://careers.hotjar.com",                        industry: "SaaS",          continent: "Europe",        remoteFriendly: true  },
  { name: "UserTesting",    careersUrl: "https://www.usertesting.com/company/careers",       industry: "SaaS",          continent: "North America", remoteFriendly: true  },
  { name: "Maze",           careersUrl: "https://maze.co/careers",                           industry: "SaaS",          continent: "Europe",        remoteFriendly: true  },
  { name: "Dovetail",       careersUrl: "https://dovetail.com/careers",                      industry: "SaaS",          continent: "Oceania",       remoteFriendly: true  },
  { name: "Coda",           careersUrl: "https://coda.io/jobs",                              industry: "SaaS",          continent: "North America", remoteFriendly: true  },
  { name: "Craft.io",       careersUrl: "https://craft.io/careers",                          industry: "SaaS",          continent: "Europe",        remoteFriendly: true  },
  { name: "Productboard",   careersUrl: "https://www.productboard.com/careers",              industry: "SaaS",          continent: "Europe",        remoteFriendly: true  },
  { name: "Aha!",           careersUrl: "https://www.aha.io/company/careers",                industry: "SaaS",          continent: "North America", remoteFriendly: true  },
  { name: "Basecamp",       careersUrl: "https://basecamp.com/about/jobs",                   industry: "SaaS",          continent: "North America", remoteFriendly: true  },
  { name: "ClickUp",        careersUrl: "https://clickup.com/careers",                       industry: "SaaS",          continent: "North America", remoteFriendly: true  },
  { name: "Todoist",        careersUrl: "https://doist.com/jobs",                            industry: "SaaS",          continent: "Europe",        remoteFriendly: true  },
  { name: "Front",          careersUrl: "https://front.com/jobs",                            industry: "SaaS",          continent: "North America", remoteFriendly: true  },
  { name: "Superhuman",     careersUrl: "https://superhuman.com/jobs",                       industry: "SaaS",          continent: "North America", remoteFriendly: false },
  { name: "Pitch",          careersUrl: "https://pitch.com/company/careers",                 industry: "SaaS",          continent: "Europe",        remoteFriendly: true  },
  { name: "Slite",          careersUrl: "https://slite.com/careers",                         industry: "SaaS",          continent: "Europe",        remoteFriendly: true  },
  { name: "Tettra",         careersUrl: "https://tettra.com/careers",                        industry: "SaaS",          continent: "North America", remoteFriendly: true  },
  { name: "Guru",           careersUrl: "https://www.getguru.com/careers",                   industry: "SaaS",          continent: "North America", remoteFriendly: true  },
  { name: "Slab",           careersUrl: "https://slab.com/jobs",                             industry: "SaaS",          continent: "North America", remoteFriendly: true  },
  { name: "Webflow",        careersUrl: "https://webflow.com/careers",                       industry: "SaaS",          continent: "North America", remoteFriendly: true  },
  { name: "Framer",         careersUrl: "https://www.framer.com/careers",                    industry: "SaaS",          continent: "Europe",        remoteFriendly: false },
  { name: "Bubble",         careersUrl: "https://bubble.io/jobs",                            industry: "SaaS",          continent: "North America", remoteFriendly: true  },
  { name: "Storyblok",      careersUrl: "https://www.storyblok.com/jobs",                    industry: "SaaS",          continent: "Europe",        remoteFriendly: true  },
  { name: "Contentful",     careersUrl: "https://www.contentful.com/careers",                industry: "SaaS",          continent: "Europe",        remoteFriendly: true  },
  { name: "Sanity",         careersUrl: "https://www.sanity.io/careers",                     industry: "SaaS",          continent: "Europe",        remoteFriendly: true  },
  { name: "Prismic",        careersUrl: "https://prismic.io/jobs",                           industry: "SaaS",          continent: "Europe",        remoteFriendly: true  },
  { name: "Ghost",          careersUrl: "https://ghost.org/jobs",                            industry: "SaaS",          continent: "Europe",        remoteFriendly: true  },
  { name: "Vero",           careersUrl: "https://www.getvero.com/jobs",                      industry: "SaaS",          continent: "Oceania",       remoteFriendly: true  },
  { name: "Customer.io",    careersUrl: "https://customer.io/jobs",                          industry: "SaaS",          continent: "North America", remoteFriendly: true  },
  { name: "Klaviyo",        careersUrl: "https://www.klaviyo.com/careers",                   industry: "SaaS",          continent: "North America", remoteFriendly: false },
  { name: "Braze",          careersUrl: "https://www.braze.com/company/careers",             industry: "SaaS",          continent: "North America", remoteFriendly: true  },

  // ─── HealthTech ───────────────────────────────────────────────────────────
  { name: "Babylon Health",  careersUrl: "https://jobs.babylonhealth.com",                   industry: "HealthTech",    continent: "Europe",        remoteFriendly: true  },
  { name: "Ro",              careersUrl: "https://ro.co/careers",                            industry: "HealthTech",    continent: "North America", remoteFriendly: false },
  { name: "Hims & Hers",     careersUrl: "https://www.forhims.com/careers",                  industry: "HealthTech",    continent: "North America", remoteFriendly: true  },
  { name: "Oscar Health",    careersUrl: "https://www.hioscar.com/careers",                  industry: "HealthTech",    continent: "North America", remoteFriendly: false },
  { name: "Noom",            careersUrl: "https://www.noom.com/careers",                     industry: "HealthTech",    continent: "North America", remoteFriendly: true  },
  { name: "Headspace",       careersUrl: "https://www.headspace.com/careers",                industry: "HealthTech",    continent: "North America", remoteFriendly: true  },
  { name: "Calm",            careersUrl: "https://www.calm.com/careers",                     industry: "HealthTech",    continent: "North America", remoteFriendly: true  },
  { name: "Lyra Health",     careersUrl: "https://www.lyrahealth.com/careers",               industry: "HealthTech",    continent: "North America", remoteFriendly: true  },
  { name: "Spring Health",   careersUrl: "https://www.springhealth.com/careers",             industry: "HealthTech",    continent: "North America", remoteFriendly: true  },
  { name: "BetterUp",        careersUrl: "https://www.betterup.com/about/careers",           industry: "HealthTech",    continent: "North America", remoteFriendly: true  },
  { name: "Teladoc",         careersUrl: "https://careers.teladochealth.com",                industry: "HealthTech",    continent: "North America", remoteFriendly: true  },
  { name: "Zocdoc",          careersUrl: "https://www.zocdoc.com/about/jobs",                industry: "HealthTech",    continent: "North America", remoteFriendly: false },
  { name: "Doximity",        careersUrl: "https://www.doximity.com/about/jobs",              industry: "HealthTech",    continent: "North America", remoteFriendly: true  },
  { name: "Tempus",          careersUrl: "https://www.tempus.com/careers",                   industry: "HealthTech",    continent: "North America", remoteFriendly: false },
  { name: "Carbon Health",   careersUrl: "https://carbonhealth.com/about/careers",           industry: "HealthTech",    continent: "North America", remoteFriendly: false },
  { name: "Cedar",           careersUrl: "https://www.cedar.com/careers",                    industry: "HealthTech",    continent: "North America", remoteFriendly: true  },
  { name: "Cityblock Health", careersUrl: "https://www.cityblock.com/careers",               industry: "HealthTech",    continent: "North America", remoteFriendly: false },
  { name: "Komodo Health",   careersUrl: "https://www.komodohealth.com/careers",             industry: "HealthTech",    continent: "North America", remoteFriendly: true  },
  { name: "Verily",          careersUrl: "https://verily.com/careers",                       industry: "HealthTech",    continent: "North America", remoteFriendly: false },
  { name: "Flatiron Health", careersUrl: "https://flatiron.com/careers",                     industry: "HealthTech",    continent: "North America", remoteFriendly: true  },
  { name: "Color Health",    careersUrl: "https://www.color.com/careers",                    industry: "HealthTech",    continent: "North America", remoteFriendly: true  },
  { name: "Brightline",      careersUrl: "https://www.hellobrightline.com/careers",          industry: "HealthTech",    continent: "North America", remoteFriendly: true  },
  { name: "Sword Health",    careersUrl: "https://swordhealth.com/careers",                  industry: "HealthTech",    continent: "Europe",        remoteFriendly: true  },
  { name: "Kry",             careersUrl: "https://www.kry.se/en/careers",                    industry: "HealthTech",    continent: "Europe",        remoteFriendly: false },
  { name: "Meditrina",       careersUrl: "https://meditrina.com/careers",                    industry: "HealthTech",    continent: "North America", remoteFriendly: true  },
  { name: "Hinge Health",    careersUrl: "https://www.hingehealth.com/company/careers",      industry: "HealthTech",    continent: "North America", remoteFriendly: true  },
  { name: "Vida Health",     careersUrl: "https://www.vida.com/careers",                     industry: "HealthTech",    continent: "North America", remoteFriendly: true  },
  { name: "Omada Health",    careersUrl: "https://www.omadahealth.com/careers",              industry: "HealthTech",    continent: "North America", remoteFriendly: true  },
  { name: "K Health",        careersUrl: "https://khealth.com/careers",                      industry: "HealthTech",    continent: "North America", remoteFriendly: true  },
  { name: "Wellthy",         careersUrl: "https://wellthy.com/careers",                      industry: "HealthTech",    continent: "North America", remoteFriendly: true  },
  { name: "Accolade",        careersUrl: "https://www.accolade.com/company/careers",         industry: "HealthTech",    continent: "North America", remoteFriendly: true  },
  { name: "Grand Rounds",    careersUrl: "https://www.grandrounds.com/careers",              industry: "HealthTech",    continent: "North America", remoteFriendly: true  },
  { name: "Forward",         careersUrl: "https://goforward.com/careers",                    industry: "HealthTech",    continent: "North America", remoteFriendly: false },
  { name: "Nuvilab",         careersUrl: "https://nuvilab.com/careers",                      industry: "HealthTech",    continent: "Asia",          remoteFriendly: false },
  { name: "Practo",          careersUrl: "https://www.practo.com/company/careers",           industry: "HealthTech",    continent: "Asia",          remoteFriendly: false },
  { name: "PharmEasy",       careersUrl: "https://pharmeasy.in/careers",                     industry: "HealthTech",    continent: "Asia",          remoteFriendly: false },
  { name: "Innovaccer",      careersUrl: "https://innovaccer.com/company/careers",           industry: "HealthTech",    continent: "Asia",          remoteFriendly: false },
  { name: "Cloudmedx",       careersUrl: "https://cloudmedxhealth.com/careers",              industry: "HealthTech",    continent: "North America", remoteFriendly: true  },
  { name: "Transcarent",     careersUrl: "https://transcarent.com/careers",                  industry: "HealthTech",    continent: "North America", remoteFriendly: true  },
  { name: "Evinova",         careersUrl: "https://www.evinova.com/careers",                  industry: "HealthTech",    continent: "Europe",        remoteFriendly: true  },
  { name: "Alan",            careersUrl: "https://jobs.alan.com",                            industry: "HealthTech",    continent: "Europe",        remoteFriendly: true  },
  { name: "Doctolib",        careersUrl: "https://careers.doctolib.com",                     industry: "HealthTech",    continent: "Europe",        remoteFriendly: false },
  { name: "Livi",            careersUrl: "https://www.livi.co.uk/about-us/careers",          industry: "HealthTech",    continent: "Europe",        remoteFriendly: false },
  { name: "MedBridge",       careersUrl: "https://www.medbridgeed.com/careers",              industry: "HealthTech",    continent: "North America", remoteFriendly: true  },
  { name: "Hippocratic AI",  careersUrl: "https://www.hippocratic.ai/careers",               industry: "HealthTech",    continent: "North America", remoteFriendly: false },
  { name: "Suki",            careersUrl: "https://www.suki.ai/careers",                      industry: "HealthTech",    continent: "North America", remoteFriendly: true  },
  { name: "Notable Health",  careersUrl: "https://www.notablehealth.com/careers",            industry: "HealthTech",    continent: "North America", remoteFriendly: true  },
  { name: "Nabla",           careersUrl: "https://www.nabla.com/about/careers",              industry: "HealthTech",    continent: "Europe",        remoteFriendly: true  },
  { name: "Abridge",         careersUrl: "https://www.abridge.com/careers",                  industry: "HealthTech",    continent: "North America", remoteFriendly: true  },
  { name: "Privia Health",   careersUrl: "https://www.priviahealth.com/careers",             industry: "HealthTech",    continent: "North America", remoteFriendly: false },
  { name: "Netsmart",        careersUrl: "https://www.ntst.com/careers",                     industry: "HealthTech",    continent: "North America", remoteFriendly: false },

  // ─── EdTech ───────────────────────────────────────────────────────────────
  { name: "Duolingo",       careersUrl: "https://careers.duolingo.com",                      industry: "EdTech",        continent: "North America", remoteFriendly: true  },
  { name: "Coursera",       careersUrl: "https://www.coursera.org/about/careers",            industry: "EdTech",        continent: "North America", remoteFriendly: true  },
  { name: "Udemy",          careersUrl: "https://about.udemy.com/jobs",                      industry: "EdTech",        continent: "North America", remoteFriendly: true  },
  { name: "Skillshare",     careersUrl: "https://www.skillshare.com/teach/careers",          industry: "EdTech",        continent: "North America", remoteFriendly: true  },
  { name: "MasterClass",    careersUrl: "https://www.masterclass.com/about/careers",         industry: "EdTech",        continent: "North America", remoteFriendly: false },
  { name: "Khan Academy",   careersUrl: "https://www.khanacademy.org/careers",               industry: "EdTech",        continent: "North America", remoteFriendly: true  },
  { name: "Chegg",          careersUrl: "https://jobs.chegg.com",                            industry: "EdTech",        continent: "North America", remoteFriendly: true  },
  { name: "Quizlet",        careersUrl: "https://quizlet.com/careers",                       industry: "EdTech",        continent: "North America", remoteFriendly: true  },
  { name: "Brainly",        careersUrl: "https://careers.brainly.com",                       industry: "EdTech",        continent: "Europe",        remoteFriendly: true  },
  { name: "Socratic",       careersUrl: "https://socratic.org/jobs",                         industry: "EdTech",        continent: "North America", remoteFriendly: true  },
  { name: "Edmodo",         careersUrl: "https://www.edmodo.com/careers",                    industry: "EdTech",        continent: "North America", remoteFriendly: false },
  { name: "Instructure",    careersUrl: "https://www.instructure.com/careers",               industry: "EdTech",        continent: "North America", remoteFriendly: true  },
  { name: "Blackboard",     careersUrl: "https://careers.anthology.com",                     industry: "EdTech",        continent: "North America", remoteFriendly: false },
  { name: "D2L",            careersUrl: "https://www.d2l.com/careers",                       industry: "EdTech",        continent: "North America", remoteFriendly: true  },
  { name: "Knewton",        careersUrl: "https://www.knewton.com/careers",                   industry: "EdTech",        continent: "North America", remoteFriendly: false },
  { name: "Newsela",        careersUrl: "https://newsela.com/about/careers",                 industry: "EdTech",        continent: "North America", remoteFriendly: true  },
  { name: "Nearpod",        careersUrl: "https://nearpod.com/careers",                       industry: "EdTech",        continent: "North America", remoteFriendly: false },
  { name: "Kahoot",         careersUrl: "https://careers.kahoot.com",                        industry: "EdTech",        continent: "Europe",        remoteFriendly: true  },
  { name: "Moodle",         careersUrl: "https://moodle.com/jobs",                           industry: "EdTech",        continent: "Oceania",       remoteFriendly: true  },
  { name: "Articulate",     careersUrl: "https://articulate.com/company/careers",            industry: "EdTech",        continent: "North America", remoteFriendly: true  },
  { name: "Thinkific",      careersUrl: "https://www.thinkific.com/careers",                 industry: "EdTech",        continent: "North America", remoteFriendly: true  },
  { name: "Teachable",      careersUrl: "https://teachable.com/company/careers",             industry: "EdTech",        continent: "North America", remoteFriendly: true  },
  { name: "Podia",          careersUrl: "https://www.podia.com/careers",                     industry: "EdTech",        continent: "North America", remoteFriendly: true  },
  { name: "Maven",          careersUrl: "https://maven.com/careers",                         industry: "EdTech",        continent: "North America", remoteFriendly: true  },
  { name: "Lambda School",  careersUrl: "https://lambdaschool.com/careers",                  industry: "EdTech",        continent: "North America", remoteFriendly: true  },
  { name: "Springboard",    careersUrl: "https://www.springboard.com/careers",               industry: "EdTech",        continent: "North America", remoteFriendly: true  },
  { name: "General Assembly", careersUrl: "https://generalassemb.ly/careers",               industry: "EdTech",        continent: "North America", remoteFriendly: false },
  { name: "Flatiron School", careersUrl: "https://flatironschool.com/careers",               industry: "EdTech",        continent: "North America", remoteFriendly: false },
  { name: "Codecademy",     careersUrl: "https://www.codecademy.com/about/careers",          industry: "EdTech",        continent: "North America", remoteFriendly: true  },
  { name: "freeCodeCamp",   careersUrl: "https://www.freecodecamp.org/news/about",           industry: "EdTech",        continent: "North America", remoteFriendly: true  },
  { name: "Scrimba",        careersUrl: "https://scrimba.com/jobs",                          industry: "EdTech",        continent: "Europe",        remoteFriendly: true  },
  { name: "Mimo",           careersUrl: "https://mimo.org/jobs",                             industry: "EdTech",        continent: "Europe",        remoteFriendly: true  },
  { name: "Brilliant",      careersUrl: "https://brilliant.org/careers",                     industry: "EdTech",        continent: "North America", remoteFriendly: true  },
  { name: "IXL Learning",   careersUrl: "https://www.ixl.com/company/careers",              industry: "EdTech",        continent: "North America", remoteFriendly: false },
  { name: "Age of Learning", careersUrl: "https://www.ageoflearning.com/careers",            industry: "EdTech",        continent: "North America", remoteFriendly: false },
  { name: "Renaissance",    careersUrl: "https://www.renaissance.com/careers",               industry: "EdTech",        continent: "North America", remoteFriendly: true  },
  { name: "PowerSchool",    careersUrl: "https://www.powerschool.com/company/careers",       industry: "EdTech",        continent: "North America", remoteFriendly: true  },
  { name: "Panorama Education", careersUrl: "https://www.panoramaed.com/careers",            industry: "EdTech",        continent: "North America", remoteFriendly: true  },
  { name: "Instructure",    careersUrl: "https://www.instructure.com/careers",               industry: "EdTech",        continent: "North America", remoteFriendly: true  },
  { name: "Formative",      careersUrl: "https://www.formative.com/jobs",                    industry: "EdTech",        continent: "North America", remoteFriendly: true  },
  { name: "Ellevation",     careersUrl: "https://ellevationeducation.com/careers",           industry: "EdTech",        continent: "North America", remoteFriendly: true  },
  { name: "Classcraft",     careersUrl: "https://www.classcraft.com/careers",                industry: "EdTech",        continent: "North America", remoteFriendly: true  },
  { name: "GoGuardian",     careersUrl: "https://www.goguardian.com/careers",                industry: "EdTech",        continent: "North America", remoteFriendly: true  },
  { name: "Tes",            careersUrl: "https://www.tes.com/jobs",                          industry: "EdTech",        continent: "Europe",        remoteFriendly: false },
  { name: "ByJu's",         careersUrl: "https://byjus.com/careers",                         industry: "EdTech",        continent: "Asia",          remoteFriendly: false },
  { name: "Unacademy",      careersUrl: "https://unacademy.com/careers",                     industry: "EdTech",        continent: "Asia",          remoteFriendly: false },
  { name: "Vedantu",        careersUrl: "https://www.vedantu.com/careers",                   industry: "EdTech",        continent: "Asia",          remoteFriendly: false },
  { name: "Toppr",          careersUrl: "https://www.toppr.com/careers",                     industry: "EdTech",        continent: "Asia",          remoteFriendly: false },
  { name: "Yuanfudao",      careersUrl: "https://www.yuanfudao.com/jobs",                    industry: "EdTech",        continent: "Asia",          remoteFriendly: false },
  { name: "Zhangmen",       careersUrl: "https://www.zhangmen.com/careers",                  industry: "EdTech",        continent: "Asia",          remoteFriendly: false },

  // ─── E-commerce ───────────────────────────────────────────────────────────
  { name: "Shopify",        careersUrl: "https://www.shopify.com/careers",                   industry: "E-commerce",    continent: "North America", remoteFriendly: true  },
  { name: "BigCommerce",    careersUrl: "https://www.bigcommerce.com/careers",               industry: "E-commerce",    continent: "North America", remoteFriendly: true  },
  { name: "WooCommerce",    careersUrl: "https://automattic.com/work-with-us",               industry: "E-commerce",    continent: "Global",        remoteFriendly: true  },
  { name: "Magento",        careersUrl: "https://www.adobe.com/careers.html",                industry: "E-commerce",    continent: "North America", remoteFriendly: true  },
  { name: "Etsy",           careersUrl: "https://careers.etsy.com",                          industry: "E-commerce",    continent: "North America", remoteFriendly: true  },
  { name: "eBay",           careersUrl: "https://careers.ebay.com",                          industry: "E-commerce",    continent: "North America", remoteFriendly: false },
  { name: "Poshmark",       careersUrl: "https://poshmark.com/careers",                      industry: "E-commerce",    continent: "North America", remoteFriendly: false },
  { name: "ThredUp",        careersUrl: "https://www.thredup.com/careers",                   industry: "E-commerce",    continent: "North America", remoteFriendly: false },
  { name: "Reverb",         careersUrl: "https://reverb.com/page/careers",                   industry: "E-commerce",    continent: "North America", remoteFriendly: true  },
  { name: "Depop",          careersUrl: "https://www.depop.com/en/jobs",                     industry: "E-commerce",    continent: "Europe",        remoteFriendly: false },
  { name: "Vinted",         careersUrl: "https://www.vinted.com/jobs",                       industry: "E-commerce",    continent: "Europe",        remoteFriendly: false },
  { name: "Farfetch",       careersUrl: "https://www.farfetch.com/careers",                  industry: "E-commerce",    continent: "Europe",        remoteFriendly: false },
  { name: "SSENSE",         careersUrl: "https://www.ssense.com/en-us/editorial/culture/jobs", industry: "E-commerce",  continent: "North America", remoteFriendly: false },
  { name: "Myntra",         careersUrl: "https://www.myntra.com/careers",                    industry: "E-commerce",    continent: "Asia",          remoteFriendly: false },
  { name: "Meesho",         careersUrl: "https://meesho.io/careers",                         industry: "E-commerce",    continent: "Asia",          remoteFriendly: false },
  { name: "Zalando",        careersUrl: "https://jobs.zalando.com",                          industry: "E-commerce",    continent: "Europe",        remoteFriendly: false },
  { name: "ASOS",           careersUrl: "https://www.asosplc.com/careers",                   industry: "E-commerce",    continent: "Europe",        remoteFriendly: false },
  { name: "Klook",          careersUrl: "https://www.klook.com/en-US/jobs",                  industry: "E-commerce",    continent: "Asia",          remoteFriendly: false },
  { name: "Lazada",         careersUrl: "https://www.lazada.com/jobs",                       industry: "E-commerce",    continent: "Asia",          remoteFriendly: false },
  { name: "Tokopedia",      careersUrl: "https://www.tokopedia.com/careers",                 industry: "E-commerce",    continent: "Asia",          remoteFriendly: false },
  { name: "Gojek",          careersUrl: "https://www.gojek.com/careers",                     industry: "E-commerce",    continent: "Asia",          remoteFriendly: false },
  { name: "Nykaa",          careersUrl: "https://nykaa.darwinbox.in/ms/candidate/careers",   industry: "E-commerce",    continent: "Asia",          remoteFriendly: false },
  { name: "Shippo",         careersUrl: "https://goshippo.com/careers",                      industry: "E-commerce",    continent: "North America", remoteFriendly: true  },
  { name: "ShipBob",        careersUrl: "https://www.shipbob.com/jobs",                      industry: "E-commerce",    continent: "North America", remoteFriendly: false },
  { name: "Loop Returns",   careersUrl: "https://www.loopreturns.com/careers",               industry: "E-commerce",    continent: "North America", remoteFriendly: true  },
  { name: "Returnly",       careersUrl: "https://returnly.com/careers",                      industry: "E-commerce",    continent: "North America", remoteFriendly: true  },
  { name: "Gorgias",        careersUrl: "https://www.gorgias.com/company/careers",           industry: "E-commerce",    continent: "North America", remoteFriendly: true  },
  { name: "Yotpo",          careersUrl: "https://www.yotpo.com/company/careers",             industry: "E-commerce",    continent: "North America", remoteFriendly: true  },
  { name: "Okendo",         careersUrl: "https://www.okendo.io/careers",                     industry: "E-commerce",    continent: "Oceania",       remoteFriendly: true  },
  { name: "Bazaarvoice",    careersUrl: "https://www.bazaarvoice.com/careers",               industry: "E-commerce",    continent: "North America", remoteFriendly: false },
  { name: "Narvar",         careersUrl: "https://www.narvar.com/careers",                    industry: "E-commerce",    continent: "North America", remoteFriendly: true  },
  { name: "AfterShip",      careersUrl: "https://www.aftership.com/jobs",                    industry: "E-commerce",    continent: "Asia",          remoteFriendly: true  },
  { name: "Privy",          careersUrl: "https://www.privy.com/careers",                     industry: "E-commerce",    continent: "North America", remoteFriendly: true  },
  { name: "Attentive",      careersUrl: "https://www.attentive.com/careers",                 industry: "E-commerce",    continent: "North America", remoteFriendly: false },
  { name: "Postscript",     careersUrl: "https://postscript.io/careers",                     industry: "E-commerce",    continent: "North America", remoteFriendly: true  },
  { name: "Drip",           careersUrl: "https://www.drip.com/careers",                      industry: "E-commerce",    continent: "North America", remoteFriendly: true  },
  { name: "ReCharge",       careersUrl: "https://rechargepayments.com/careers",              industry: "E-commerce",    continent: "North America", remoteFriendly: true  },
  { name: "Bold Commerce",  careersUrl: "https://boldcommerce.com/careers",                  industry: "E-commerce",    continent: "North America", remoteFriendly: true  },
  { name: "Skio",           careersUrl: "https://www.skio.com/careers",                      industry: "E-commerce",    continent: "North America", remoteFriendly: true  },
  { name: "Ordergroove",    careersUrl: "https://www.ordergroove.com/careers",               industry: "E-commerce",    continent: "North America", remoteFriendly: true  },

  // ─── AI / ML ──────────────────────────────────────────────────────────────
  { name: "Anthropic",      careersUrl: "https://boards.greenhouse.io/anthropic",            industry: "AI / ML",       continent: "North America", remoteFriendly: true  },
  { name: "OpenAI",         careersUrl: "https://openai.com/careers",                        industry: "AI / ML",       continent: "North America", remoteFriendly: false },
  { name: "Cohere",         careersUrl: "https://cohere.com/careers",                        industry: "AI / ML",       continent: "North America", remoteFriendly: true  },
  { name: "Mistral AI",     careersUrl: "https://jobs.lever.co/mistral",                     industry: "AI / ML",       continent: "Europe",        remoteFriendly: false },
  { name: "Inflection AI",  careersUrl: "https://inflection.ai/careers",                     industry: "AI / ML",       continent: "North America", remoteFriendly: false },
  { name: "Stability AI",   careersUrl: "https://stability.ai/careers",                      industry: "AI / ML",       continent: "Europe",        remoteFriendly: true  },
  { name: "Midjourney",     careersUrl: "https://www.midjourney.com/jobs",                   industry: "AI / ML",       continent: "North America", remoteFriendly: false },
  { name: "Runway",         careersUrl: "https://runwayml.com/careers",                      industry: "AI / ML",       continent: "North America", remoteFriendly: false },
  { name: "Hugging Face",   careersUrl: "https://apply.workable.com/hugging-face",           industry: "AI / ML",       continent: "North America", remoteFriendly: true  },
  { name: "Scale AI",       careersUrl: "https://scale.com/careers",                         industry: "AI / ML",       continent: "North America", remoteFriendly: false },
  { name: "Labelbox",       careersUrl: "https://labelbox.com/careers",                      industry: "AI / ML",       continent: "North America", remoteFriendly: true  },
  { name: "Weights & Biases", careersUrl: "https://wandb.ai/site/careers",                   industry: "AI / ML",       continent: "North America", remoteFriendly: true  },
  { name: "Replicate",      careersUrl: "https://replicate.com/jobs",                        industry: "AI / ML",       continent: "North America", remoteFriendly: true  },
  { name: "Together AI",    careersUrl: "https://www.together.ai/careers",                   industry: "AI / ML",       continent: "North America", remoteFriendly: false },
  { name: "Perplexity AI",  careersUrl: "https://www.perplexity.ai/hub/careers",             industry: "AI / ML",       continent: "North America", remoteFriendly: false },
  { name: "Adept AI",       careersUrl: "https://www.adept.ai/careers",                      industry: "AI / ML",       continent: "North America", remoteFriendly: false },
  { name: "Character.AI",   careersUrl: "https://character.ai/careers",                      industry: "AI / ML",       continent: "North America", remoteFriendly: false },
  { name: "Pika",           careersUrl: "https://pika.art/careers",                          industry: "AI / ML",       continent: "North America", remoteFriendly: false },
  { name: "ElevenLabs",     careersUrl: "https://jobs.ashbyhq.com/elevenlabs",               industry: "AI / ML",       continent: "Europe",        remoteFriendly: true  },
  { name: "Synthesia",      careersUrl: "https://www.synthesia.io/careers",                  industry: "AI / ML",       continent: "Europe",        remoteFriendly: true  },
  { name: "DeepL",          careersUrl: "https://www.deepl.com/careers",                     industry: "AI / ML",       continent: "Europe",        remoteFriendly: true  },
  { name: "DataRobot",      careersUrl: "https://www.datarobot.com/careers",                 industry: "AI / ML",       continent: "North America", remoteFriendly: true  },
  { name: "H2O.ai",         careersUrl: "https://www.h2o.ai/careers",                        industry: "AI / ML",       continent: "North America", remoteFriendly: true  },
  { name: "C3.ai",          careersUrl: "https://c3.ai/company/careers",                     industry: "AI / ML",       continent: "North America", remoteFriendly: false },
  { name: "SambaNova",      careersUrl: "https://sambanova.ai/careers",                      industry: "AI / ML",       continent: "North America", remoteFriendly: false },
  { name: "Cerebras",       careersUrl: "https://www.cerebras.ai/careers",                   industry: "AI / ML",       continent: "North America", remoteFriendly: false },
  { name: "Groq",           careersUrl: "https://groq.com/careers",                          industry: "AI / ML",       continent: "North America", remoteFriendly: false },
  { name: "Fireworks AI",   careersUrl: "https://fireworks.ai/careers",                      industry: "AI / ML",       continent: "North America", remoteFriendly: true  },
  { name: "Modal",          careersUrl: "https://modal.com/careers",                         industry: "AI / ML",       continent: "North America", remoteFriendly: true  },
  { name: "Baseten",        careersUrl: "https://www.baseten.co/careers",                    industry: "AI / ML",       continent: "North America", remoteFriendly: true  },
  { name: "Fal.ai",         careersUrl: "https://fal.ai/jobs",                               industry: "AI / ML",       continent: "Europe",        remoteFriendly: true  },
  { name: "LangChain",      careersUrl: "https://langchain.com/careers",                     industry: "AI / ML",       continent: "North America", remoteFriendly: true  },
  { name: "LlamaIndex",     careersUrl: "https://llamaindex.ai/careers",                     industry: "AI / ML",       continent: "North America", remoteFriendly: true  },
  { name: "Weaviate",       careersUrl: "https://weaviate.io/company/careers",               industry: "AI / ML",       continent: "Europe",        remoteFriendly: true  },
  { name: "Pinecone",       careersUrl: "https://www.pinecone.io/careers",                   industry: "AI / ML",       continent: "North America", remoteFriendly: true  },
  { name: "Chroma",         careersUrl: "https://www.trychroma.com/careers",                 industry: "AI / ML",       continent: "North America", remoteFriendly: true  },
  { name: "Qdrant",         careersUrl: "https://qdrant.tech/careers",                       industry: "AI / ML",       continent: "Europe",        remoteFriendly: true  },
  { name: "Jasper",         careersUrl: "https://www.jasper.ai/careers",                     industry: "AI / ML",       continent: "North America", remoteFriendly: true  },
  { name: "Copy.ai",        careersUrl: "https://www.copy.ai/careers",                       industry: "AI / ML",       continent: "North America", remoteFriendly: true  },
  { name: "Writer",         careersUrl: "https://writer.com/careers",                        industry: "AI / ML",       continent: "North America", remoteFriendly: true  },
  { name: "Tome",           careersUrl: "https://tome.app/careers",                          industry: "AI / ML",       continent: "North America", remoteFriendly: false },
  { name: "Glean",          careersUrl: "https://www.glean.com/careers",                     industry: "AI / ML",       continent: "North America", remoteFriendly: false },
  { name: "Moveworks",      careersUrl: "https://www.moveworks.com/careers",                 industry: "AI / ML",       continent: "North America", remoteFriendly: false },
  { name: "Leena AI",       careersUrl: "https://leena.ai/careers",                          industry: "AI / ML",       continent: "Asia",          remoteFriendly: false },
  { name: "Kore.ai",        careersUrl: "https://kore.ai/company/careers",                   industry: "AI / ML",       continent: "North America", remoteFriendly: false },
  { name: "Rasa",           careersUrl: "https://rasa.com/jobs",                             industry: "AI / ML",       continent: "Europe",        remoteFriendly: true  },
  { name: "Arcee AI",       careersUrl: "https://arcee.ai/careers",                          industry: "AI / ML",       continent: "North America", remoteFriendly: true  },
  { name: "Contextual AI",  careersUrl: "https://contextual.ai/careers",                     industry: "AI / ML",       continent: "North America", remoteFriendly: false },
  { name: "Vectara",        careersUrl: "https://vectara.com/jobs",                          industry: "AI / ML",       continent: "North America", remoteFriendly: true  },
  { name: "Cohere",         careersUrl: "https://cohere.com/careers",                        industry: "AI / ML",       continent: "North America", remoteFriendly: true  },
  { name: "Inflection AI",  careersUrl: "https://inflection.ai/careers",                     industry: "AI / ML",       continent: "North America", remoteFriendly: false },

  // ─── Crypto / Web3 ────────────────────────────────────────────────────────
  { name: "Coinbase",       careersUrl: "https://www.coinbase.com/careers",                  industry: "Crypto / Web3", continent: "North America", remoteFriendly: true  },
  { name: "Binance",        careersUrl: "https://www.binance.com/en/careers",                industry: "Crypto / Web3", continent: "Global",        remoteFriendly: true  },
  { name: "Kraken",         careersUrl: "https://www.kraken.com/careers",                    industry: "Crypto / Web3", continent: "North America", remoteFriendly: true  },
  { name: "Gemini",         careersUrl: "https://www.gemini.com/careers",                    industry: "Crypto / Web3", continent: "North America", remoteFriendly: true  },
  { name: "FTX",            careersUrl: "https://ftx.com/careers",                           industry: "Crypto / Web3", continent: "Global",        remoteFriendly: true  },
  { name: "Chainalysis",    careersUrl: "https://www.chainalysis.com/careers",               industry: "Crypto / Web3", continent: "North America", remoteFriendly: true  },
  { name: "Alchemy",        careersUrl: "https://www.alchemy.com/careers",                   industry: "Crypto / Web3", continent: "North America", remoteFriendly: true  },
  { name: "Infura",         careersUrl: "https://www.infura.io/careers",                     industry: "Crypto / Web3", continent: "North America", remoteFriendly: true  },
  { name: "Moralis",        careersUrl: "https://moralis.io/careers",                        industry: "Crypto / Web3", continent: "Europe",        remoteFriendly: true  },
  { name: "Consensys",      careersUrl: "https://consensys.io/open-roles",                   industry: "Crypto / Web3", continent: "North America", remoteFriendly: true  },
  { name: "ConsenSys Mesh", careersUrl: "https://mesh.xyz/careers",                          industry: "Crypto / Web3", continent: "North America", remoteFriendly: true  },
  { name: "dYdX",           careersUrl: "https://dydx.exchange/careers",                     industry: "Crypto / Web3", continent: "North America", remoteFriendly: true  },
  { name: "Uniswap",        careersUrl: "https://boards.greenhouse.io/uniswaplabs",          industry: "Crypto / Web3", continent: "North America", remoteFriendly: true  },
  { name: "Aave",           careersUrl: "https://jobs.lever.co/aave",                        industry: "Crypto / Web3", continent: "Europe",        remoteFriendly: true  },
  { name: "MakerDAO",       careersUrl: "https://makerdao.com/en/careers",                   industry: "Crypto / Web3", continent: "Global",        remoteFriendly: true  },
  { name: "Compound",       careersUrl: "https://compound.finance/about",                    industry: "Crypto / Web3", continent: "North America", remoteFriendly: true  },
  { name: "Anchorage",      careersUrl: "https://www.anchorage.com/company/careers",         industry: "Crypto / Web3", continent: "North America", remoteFriendly: false },
  { name: "Figment",        careersUrl: "https://www.figment.io/careers",                    industry: "Crypto / Web3", continent: "North America", remoteFriendly: true  },
  { name: "Ledger",         careersUrl: "https://jobs.lever.co/ledger",                      industry: "Crypto / Web3", continent: "Europe",        remoteFriendly: false },
  { name: "Trezor",         careersUrl: "https://trezor.io/jobs",                            industry: "Crypto / Web3", continent: "Europe",        remoteFriendly: false },
  { name: "Fireblocks",     careersUrl: "https://www.fireblocks.com/careers",                industry: "Crypto / Web3", continent: "Europe",        remoteFriendly: false },
  { name: "BitGo",          careersUrl: "https://www.bitgo.com/careers",                     industry: "Crypto / Web3", continent: "North America", remoteFriendly: true  },
  { name: "Blockdaemon",    careersUrl: "https://www.blockdaemon.com/careers",               industry: "Crypto / Web3", continent: "North America", remoteFriendly: true  },
  { name: "Gauntlet",       careersUrl: "https://jobs.lever.co/gauntlet",                    industry: "Crypto / Web3", continent: "North America", remoteFriendly: true  },
  { name: "Messari",        careersUrl: "https://messari.io/careers",                        industry: "Crypto / Web3", continent: "North America", remoteFriendly: true  },
  { name: "Nansen",         careersUrl: "https://www.nansen.ai/careers",                     industry: "Crypto / Web3", continent: "Global",        remoteFriendly: true  },
  { name: "Dune Analytics", careersUrl: "https://boards.greenhouse.io/duneanalytics",        industry: "Crypto / Web3", continent: "Europe",        remoteFriendly: true  },
  { name: "Token Terminal", careersUrl: "https://tokenterminal.com/careers",                 industry: "Crypto / Web3", continent: "Europe",        remoteFriendly: true  },
  { name: "OpenSea",        careersUrl: "https://opensea.io/careers",                        industry: "Crypto / Web3", continent: "North America", remoteFriendly: true  },
  { name: "Magic Eden",     careersUrl: "https://magiceden.io/careers",                      industry: "Crypto / Web3", continent: "North America", remoteFriendly: true  },
  { name: "SuperRare",      careersUrl: "https://superrare.com/careers",                     industry: "Crypto / Web3", continent: "North America", remoteFriendly: true  },
  { name: "Rarible",        careersUrl: "https://rarible.com/careers",                       industry: "Crypto / Web3", continent: "Europe",        remoteFriendly: true  },
  { name: "Foundation",     careersUrl: "https://jobs.ashbyhq.com/foundation",               industry: "Crypto / Web3", continent: "North America", remoteFriendly: true  },
  { name: "Zora",           careersUrl: "https://zora.co/careers",                           industry: "Crypto / Web3", continent: "North America", remoteFriendly: true  },
  { name: "Manifold",       careersUrl: "https://manifold.xyz/jobs",                         industry: "Crypto / Web3", continent: "North America", remoteFriendly: true  },
  { name: "Phantom",        careersUrl: "https://phantom.app/careers",                       industry: "Crypto / Web3", continent: "North America", remoteFriendly: true  },
  { name: "Rainbow",        careersUrl: "https://rainbow.me/jobs",                           industry: "Crypto / Web3", continent: "North America", remoteFriendly: true  },
  { name: "Zerion",         careersUrl: "https://zerion.io/careers",                         industry: "Crypto / Web3", continent: "Europe",        remoteFriendly: true  },
  { name: "MetaMask",       careersUrl: "https://consensys.io/open-roles",                   industry: "Crypto / Web3", continent: "North America", remoteFriendly: true  },
  { name: "Argent",         careersUrl: "https://www.argent.xyz/careers",                    industry: "Crypto / Web3", continent: "Europe",        remoteFriendly: true  },
  { name: "Gnosis",         careersUrl: "https://www.gnosis.io/careers",                     industry: "Crypto / Web3", continent: "Europe",        remoteFriendly: true  },
  { name: "Aztec",          careersUrl: "https://aztec.network/careers",                     industry: "Crypto / Web3", continent: "Europe",        remoteFriendly: true  },
  { name: "StarkWare",      careersUrl: "https://starkware.co/careers",                      industry: "Crypto / Web3", continent: "Europe",        remoteFriendly: false },
  { name: "Matter Labs",    careersUrl: "https://matterlabs.notion.site/",                   industry: "Crypto / Web3", continent: "Europe",        remoteFriendly: true  },
  { name: "Optimism",       careersUrl: "https://jobs.optimism.io",                          industry: "Crypto / Web3", continent: "North America", remoteFriendly: true  },
  { name: "Arbitrum",       careersUrl: "https://arbitrum.foundation/careers",               industry: "Crypto / Web3", continent: "North America", remoteFriendly: true  },
  { name: "Polygon",        careersUrl: "https://polygon.technology/careers",                industry: "Crypto / Web3", continent: "Asia",          remoteFriendly: true  },
  { name: "Near Protocol",  careersUrl: "https://jobs.ashbyhq.com/near",                     industry: "Crypto / Web3", continent: "Global",        remoteFriendly: true  },
  { name: "Solana Labs",    careersUrl: "https://solana.com/about#jobs",                     industry: "Crypto / Web3", continent: "North America", remoteFriendly: true  },
  { name: "Ava Labs",       careersUrl: "https://boards.greenhouse.io/avalabs",              industry: "Crypto / Web3", continent: "North America", remoteFriendly: true  },

  // ─── Media ────────────────────────────────────────────────────────────────
  { name: "Spotify",        careersUrl: "https://www.lifeatspotify.com/jobs",                industry: "Media",         continent: "Europe",        remoteFriendly: true  },
  { name: "Netflix",        careersUrl: "https://jobs.netflix.com",                          industry: "Media",         continent: "North America", remoteFriendly: false },
  { name: "Hulu",           careersUrl: "https://careers.hulu.com",                          industry: "Media",         continent: "North America", remoteFriendly: false },
  { name: "Twitch",         careersUrl: "https://www.twitch.tv/jobs",                        industry: "Media",         continent: "North America", remoteFriendly: false },
  { name: "Discord",        careersUrl: "https://discord.com/jobs",                          industry: "Media",         continent: "North America", remoteFriendly: false },
  { name: "Pinterest",      careersUrl: "https://www.pinterestcareers.com",                  industry: "Media",         continent: "North America", remoteFriendly: true  },
  { name: "Snap",           careersUrl: "https://careers.snap.com",                          industry: "Media",         continent: "North America", remoteFriendly: false },
  { name: "Reddit",         careersUrl: "https://boards.greenhouse.io/reddit",               industry: "Media",         continent: "North America", remoteFriendly: true  },
  { name: "Tumblr",         careersUrl: "https://automattic.com/work-with-us",               industry: "Media",         continent: "North America", remoteFriendly: true  },
  { name: "Medium",         careersUrl: "https://medium.com/jobs-at-medium",                 industry: "Media",         continent: "North America", remoteFriendly: true  },
  { name: "Substack",       careersUrl: "https://substack.com/jobs",                         industry: "Media",         continent: "North America", remoteFriendly: true  },
  { name: "SoundCloud",     careersUrl: "https://careers.soundcloud.com",                    industry: "Media",         continent: "Europe",        remoteFriendly: false },
  { name: "Deezer",         careersUrl: "https://www.deezer.com/en/company/careers",         industry: "Media",         continent: "Europe",        remoteFriendly: false },
  { name: "TIDAL",          careersUrl: "https://www.tidal.com/about/jobs",                  industry: "Media",         continent: "Europe",        remoteFriendly: false },
  { name: "Bandcamp",       careersUrl: "https://bandcamp.com/jobs",                         industry: "Media",         continent: "North America", remoteFriendly: true  },
  { name: "Patreon",        careersUrl: "https://www.patreon.com/careers",                   industry: "Media",         continent: "North America", remoteFriendly: true  },
  { name: "Anchor",         careersUrl: "https://www.lifeatspotify.com/jobs",                industry: "Media",         continent: "North America", remoteFriendly: true  },
  { name: "Podimo",         careersUrl: "https://podimo.com/jobs",                           industry: "Media",         continent: "Europe",        remoteFriendly: false },
  { name: "Acast",          careersUrl: "https://www.acast.com/en/jobs",                     industry: "Media",         continent: "Europe",        remoteFriendly: false },
  { name: "Plex",           careersUrl: "https://www.plex.tv/about/careers",                 industry: "Media",         continent: "North America", remoteFriendly: true  },
  { name: "Vimeo",          careersUrl: "https://vimeo.com/jobs",                            industry: "Media",         continent: "North America", remoteFriendly: true  },
  { name: "Wistia",         careersUrl: "https://wistia.com/jobs",                           industry: "Media",         continent: "North America", remoteFriendly: false },
  { name: "Brightcove",     careersUrl: "https://www.brightcove.com/en/company/careers",     industry: "Media",         continent: "North America", remoteFriendly: false },
  { name: "Kaltura",        careersUrl: "https://corp.kaltura.com/careers",                  industry: "Media",         continent: "North America", remoteFriendly: false },
  { name: "Streamable",     careersUrl: "https://streamable.com/jobs",                       industry: "Media",         continent: "North America", remoteFriendly: true  },
  { name: "Mux",            careersUrl: "https://www.mux.com/jobs",                          industry: "Media",         continent: "North America", remoteFriendly: true  },
  { name: "Dailymotion",    careersUrl: "https://www.dailymotion.com/careers",               industry: "Media",         continent: "Europe",        remoteFriendly: false },
  { name: "Bytedance",      careersUrl: "https://jobs.bytedance.com",                        industry: "Media",         continent: "Asia",          remoteFriendly: false },
  { name: "Kuaishou",       careersUrl: "https://www.kuaishou.com/careers",                  industry: "Media",         continent: "Asia",          remoteFriendly: false },
  { name: "Giphy",          careersUrl: "https://giphy.com/jobs",                            industry: "Media",         continent: "North America", remoteFriendly: false },
  { name: "Flipboard",      careersUrl: "https://flipboard.com/careers",                     industry: "Media",         continent: "North America", remoteFriendly: true  },
  { name: "Feedly",         careersUrl: "https://feedly.com/i/careers",                      industry: "Media",         continent: "North America", remoteFriendly: true  },
  { name: "Artifact",       careersUrl: "https://artifact.news/careers",                     industry: "Media",         continent: "North America", remoteFriendly: true  },
  { name: "Ground News",    careersUrl: "https://ground.news/careers",                       industry: "Media",         continent: "North America", remoteFriendly: true  },
  { name: "Pocket",         careersUrl: "https://getpocket.com/jobs",                        industry: "Media",         continent: "North America", remoteFriendly: true  },
  { name: "Instapaper",     careersUrl: "https://www.instapaper.com/about",                  industry: "Media",         continent: "North America", remoteFriendly: true  },
  { name: "Matter",         careersUrl: "https://hq.getmatter.com/careers",                  industry: "Media",         continent: "North America", remoteFriendly: true  },
  { name: "Glow",           careersUrl: "https://www.glowstudios.com/careers",               industry: "Media",         continent: "North America", remoteFriendly: false },
  { name: "Canva",          careersUrl: "https://www.canva.com/careers",                     industry: "Media",         continent: "Oceania",       remoteFriendly: true  },
  { name: "Adobe",          careersUrl: "https://www.adobe.com/careers.html",                industry: "Media",         continent: "North America", remoteFriendly: false },
  { name: "Sketchfab",      careersUrl: "https://sketchfab.com/jobs",                        industry: "Media",         continent: "Europe",        remoteFriendly: true  },
  { name: "ArtStation",     careersUrl: "https://www.artstation.com/jobs",                   industry: "Media",         continent: "North America", remoteFriendly: false },
  { name: "Behance",        careersUrl: "https://www.adobe.com/careers.html",                industry: "Media",         continent: "North America", remoteFriendly: false },
  { name: "Dribbble",       careersUrl: "https://dribbble.com/jobs",                         industry: "Media",         continent: "North America", remoteFriendly: true  },
  { name: "Pixelmator",     careersUrl: "https://www.pixelmator.com/jobs",                   industry: "Media",         continent: "Europe",        remoteFriendly: false },
  { name: "Affinity",       careersUrl: "https://affinity.serif.com/en-us/careers",          industry: "Media",         continent: "Europe",        remoteFriendly: false },
  { name: "InVision",       careersUrl: "https://www.invisionapp.com/careers",               industry: "Media",         continent: "North America", remoteFriendly: true  },
  { name: "Zeplin",         careersUrl: "https://zeplin.io/jobs",                            industry: "Media",         continent: "Europe",        remoteFriendly: true  },
  { name: "Abstract",       careersUrl: "https://www.abstract.com/company/jobs",             industry: "Media",         continent: "North America", remoteFriendly: true  },
  { name: "Readymag",       careersUrl: "https://readymag.com/jobs",                         industry: "Media",         continent: "Europe",        remoteFriendly: true  },

  // ─── Gaming ───────────────────────────────────────────────────────────────
  { name: "Unity",          careersUrl: "https://careers.unity.com",                         industry: "Gaming",        continent: "North America", remoteFriendly: true  },
  { name: "Epic Games",     careersUrl: "https://www.epicgames.com/site/en-US/careers",      industry: "Gaming",        continent: "North America", remoteFriendly: true  },
  { name: "Roblox",         careersUrl: "https://careers.roblox.com",                        industry: "Gaming",        continent: "North America", remoteFriendly: false },
  { name: "Niantic",        careersUrl: "https://www.nianticlabs.com/careers",               industry: "Gaming",        continent: "North America", remoteFriendly: false },
  { name: "Riot Games",     careersUrl: "https://www.riotgames.com/en/work-with-us",         industry: "Gaming",        continent: "North America", remoteFriendly: false },
  { name: "Supercell",      careersUrl: "https://supercell.com/en/jobs",                     industry: "Gaming",        continent: "Europe",        remoteFriendly: false },
  { name: "Rovio",          careersUrl: "https://www.rovio.com/careers",                     industry: "Gaming",        continent: "Europe",        remoteFriendly: false },
  { name: "King",           careersUrl: "https://careers.king.com",                          industry: "Gaming",        continent: "Europe",        remoteFriendly: false },
  { name: "Ubisoft",        careersUrl: "https://www.ubisoft.com/en-us/careers",             industry: "Gaming",        continent: "Europe",        remoteFriendly: false },
  { name: "CD Projekt Red", careersUrl: "https://www.cdprojektred.com/en/career",            industry: "Gaming",        continent: "Europe",        remoteFriendly: false },
  { name: "Digital Extremes", careersUrl: "https://www.digitalextremes.com/careers",         industry: "Gaming",        continent: "North America", remoteFriendly: false },
  { name: "Bungie",         careersUrl: "https://www.bungie.net/en/AboutUs/Careers",         industry: "Gaming",        continent: "North America", remoteFriendly: true  },
  { name: "Insomniac Games", careersUrl: "https://insomniac.games/careers",                  industry: "Gaming",        continent: "North America", remoteFriendly: false },
  { name: "Naughty Dog",    careersUrl: "https://www.naughtydog.com/careers",                industry: "Gaming",        continent: "North America", remoteFriendly: false },
  { name: "Respawn Entertainment", careersUrl: "https://www.ea.com/careers",                 industry: "Gaming",        continent: "North America", remoteFriendly: false },
  { name: "Infinity Ward",  careersUrl: "https://careers.activision.com",                    industry: "Gaming",        continent: "North America", remoteFriendly: false },
  { name: "Guerrilla Games", careersUrl: "https://www.guerrilla-games.com/join",             industry: "Gaming",        continent: "Europe",        remoteFriendly: false },
  { name: "IO Interactive", careersUrl: "https://ioi.dk/careers",                            industry: "Gaming",        continent: "Europe",        remoteFriendly: false },
  { name: "Remedy Entertainment", careersUrl: "https://www.remedygames.com/careers",         industry: "Gaming",        continent: "Europe",        remoteFriendly: false },
  { name: "DICE",           careersUrl: "https://www.dice.se/careers",                       industry: "Gaming",        continent: "Europe",        remoteFriendly: false },
  { name: "Paradox Interactive", careersUrl: "https://career.paradoxinteractive.com",        industry: "Gaming",        continent: "Europe",        remoteFriendly: false },
  { name: "Mojang Studios", careersUrl: "https://careers.microsoft.com",                     industry: "Gaming",        continent: "Europe",        remoteFriendly: false },
  { name: "Devolver Digital", careersUrl: "https://www.devolverdigital.com/jobs",            industry: "Gaming",        continent: "North America", remoteFriendly: true  },
  { name: "Team17",         careersUrl: "https://www.team17.com/careers",                    industry: "Gaming",        continent: "Europe",        remoteFriendly: false },
  { name: "tinyBuild",      careersUrl: "https://www.tinybuild.com/careers",                 industry: "Gaming",        continent: "North America", remoteFriendly: false },
  { name: "Raw Fury",       careersUrl: "https://rawfury.com/jobs",                          industry: "Gaming",        continent: "Europe",        remoteFriendly: true  },
  { name: "Klei Entertainment", careersUrl: "https://www.klei.com/jobs",                     industry: "Gaming",        continent: "North America", remoteFriendly: false },
  { name: "Massivemusic",   careersUrl: "https://massivemusic.com/careers",                  industry: "Gaming",        continent: "Europe",        remoteFriendly: false },
  { name: "Playtika",       careersUrl: "https://www.playtika.com/careers",                  industry: "Gaming",        continent: "Europe",        remoteFriendly: false },
  { name: "Nexon",          careersUrl: "https://careers.nexon.com",                         industry: "Gaming",        continent: "Asia",          remoteFriendly: false },
  { name: "Netease Games",  careersUrl: "https://game.netease.com/careers",                  industry: "Gaming",        continent: "Asia",          remoteFriendly: false },
  { name: "miHoYo",         careersUrl: "https://www.mihoyo.com/en/jobs",                    industry: "Gaming",        continent: "Asia",          remoteFriendly: false },
  { name: "Sea Limited",    careersUrl: "https://careers.sea.com",                           industry: "Gaming",        continent: "Asia",          remoteFriendly: false },
  { name: "Garena",         careersUrl: "https://careers.garena.com",                        industry: "Gaming",        continent: "Asia",          remoteFriendly: false },
  { name: "Krafton",        careersUrl: "https://careers.krafton.com",                       industry: "Gaming",        continent: "Asia",          remoteFriendly: false },
  { name: "PUBG Corporation", careersUrl: "https://careers.krafton.com",                     industry: "Gaming",        continent: "Asia",          remoteFriendly: false },
  { name: "Playdead",       careersUrl: "https://playdead.com/jobs",                         industry: "Gaming",        continent: "Europe",        remoteFriendly: false },
  { name: "Codemasters",    careersUrl: "https://www.codemasters.com/careers",               industry: "Gaming",        continent: "Europe",        remoteFriendly: false },
  { name: "Frontier Developments", careersUrl: "https://www.frontier.co.uk/careers",        industry: "Gaming",        continent: "Europe",        remoteFriendly: false },
  { name: "Playground Games", careersUrl: "https://careers.microsoft.com",                   industry: "Gaming",        continent: "Europe",        remoteFriendly: false },
  { name: "Splash Damage",  careersUrl: "https://www.splashdamage.com/careers",              industry: "Gaming",        continent: "Europe",        remoteFriendly: false },
  { name: "Improbable",     careersUrl: "https://improbable.io/careers",                     industry: "Gaming",        continent: "Europe",        remoteFriendly: false },
  { name: "Zinga",          careersUrl: "https://careers.zynga.com",                         industry: "Gaming",        continent: "North America", remoteFriendly: true  },
  { name: "Jam City",       careersUrl: "https://www.jamcity.com/careers",                   industry: "Gaming",        continent: "North America", remoteFriendly: false },
  { name: "Social Point",   careersUrl: "https://www.socialpoint.es/careers",                industry: "Gaming",        continent: "Europe",        remoteFriendly: false },
  { name: "Tripledot Studios", careersUrl: "https://tripledot.com/jobs",                     industry: "Gaming",        continent: "Europe",        remoteFriendly: false },
  { name: "Wildlife Studios", careersUrl: "https://wildlifestudios.com/careers",             industry: "Gaming",        continent: "Latin America", remoteFriendly: false },
  { name: "Voodoo",         careersUrl: "https://jobs.voodoo.io",                            industry: "Gaming",        continent: "Europe",        remoteFriendly: false },
  { name: "Homa Games",     careersUrl: "https://homagames.com/careers",                     industry: "Gaming",        continent: "Europe",        remoteFriendly: true  },

  // ─── Climate ──────────────────────────────────────────────────────────────
  { name: "Climeworks",     careersUrl: "https://www.climeworks.com/careers",                industry: "Climate",       continent: "Europe",        remoteFriendly: false },
  { name: "Carbon Clean",   careersUrl: "https://carbonclean.com/careers",                   industry: "Climate",       continent: "Europe",        remoteFriendly: false },
  { name: "Pachama",        careersUrl: "https://pachama.com/careers",                       industry: "Climate",       continent: "North America", remoteFriendly: true  },
  { name: "Stripe Climate", careersUrl: "https://stripe.com/jobs",                           industry: "Climate",       continent: "North America", remoteFriendly: true  },
  { name: "Watershed",      careersUrl: "https://watershed.com/careers",                     industry: "Climate",       continent: "North America", remoteFriendly: true  },
  { name: "Persefoni",      careersUrl: "https://persefoni.com/careers",                     industry: "Climate",       continent: "North America", remoteFriendly: true  },
  { name: "Greenbacker",    careersUrl: "https://www.greenbackercapital.com/careers",        industry: "Climate",       continent: "North America", remoteFriendly: false },
  { name: "Arcadia",        careersUrl: "https://www.arcadia.com/careers",                   industry: "Climate",       continent: "North America", remoteFriendly: true  },
  { name: "Bright Power",   careersUrl: "https://www.brightpower.com/careers",               industry: "Climate",       continent: "North America", remoteFriendly: false },
  { name: "Xpansiv",        careersUrl: "https://xpansiv.com/careers",                       industry: "Climate",       continent: "North America", remoteFriendly: false },
  { name: "South Pole",     careersUrl: "https://www.southpole.com/careers",                 industry: "Climate",       continent: "Europe",        remoteFriendly: false },
  { name: "Gold Standard",  careersUrl: "https://www.goldstandard.org/about/careers",        industry: "Climate",       continent: "Europe",        remoteFriendly: false },
  { name: "Sylvera",        careersUrl: "https://sylvera.com/careers",                       industry: "Climate",       continent: "Europe",        remoteFriendly: true  },
  { name: "Rubicon Carbon",careersUrl: "https://www.rubiconcarbon.com/careers",              industry: "Climate",       continent: "North America", remoteFriendly: false },
  { name: "Terrapass",      careersUrl: "https://www.terrapass.com/about/careers",           industry: "Climate",       continent: "North America", remoteFriendly: false },
  { name: "Cool Effect",    careersUrl: "https://www.cooleffect.org/careers",                industry: "Climate",       continent: "North America", remoteFriendly: true  },
  { name: "Carbon Direct",  careersUrl: "https://carbon-direct.com/careers",                 industry: "Climate",       continent: "North America", remoteFriendly: true  },
  { name: "Heirloom",       careersUrl: "https://www.heirloomcarbon.com/careers",            industry: "Climate",       continent: "North America", remoteFriendly: false },
  { name: "Running Tide",   careersUrl: "https://www.runningtide.com/careers",               industry: "Climate",       continent: "North America", remoteFriendly: false },
  { name: "Charm Industrial", careersUrl: "https://charmindustrial.com/jobs",                industry: "Climate",       continent: "North America", remoteFriendly: false },
  { name: "Blueprint Power", careersUrl: "https://blueprintpower.com/careers",               industry: "Climate",       continent: "North America", remoteFriendly: false },
  { name: "Helion Energy",  careersUrl: "https://www.helionenergy.com/careers",              industry: "Climate",       continent: "North America", remoteFriendly: false },
  { name: "Commonwealth Fusion", careersUrl: "https://cfs.energy/careers",                  industry: "Climate",       continent: "North America", remoteFriendly: false },
  { name: "TAE Technologies", careersUrl: "https://www.tae.com/careers",                    industry: "Climate",       continent: "North America", remoteFriendly: false },
  { name: "Redwood Materials", careersUrl: "https://www.redwoodmaterials.com/careers",       industry: "Climate",       continent: "North America", remoteFriendly: false },
  { name: "Li-Cycle",       careersUrl: "https://li-cycle.com/careers",                     industry: "Climate",       continent: "North America", remoteFriendly: false },
  { name: "Our Next Energy", careersUrl: "https://ournenergy.com/careers",                   industry: "Climate",       continent: "North America", remoteFriendly: false },
  { name: "Northvolt",      careersUrl: "https://northvolt.com/careers",                     industry: "Climate",       continent: "Europe",        remoteFriendly: false },
  { name: "Volta Charging", careersUrl: "https://voltacharging.com/careers",                 industry: "Climate",       continent: "North America", remoteFriendly: false },
  { name: "EVgo",           careersUrl: "https://www.evgo.com/about/careers",                industry: "Climate",       continent: "North America", remoteFriendly: false },
  { name: "ChargePoint",    careersUrl: "https://www.chargepoint.com/careers",               industry: "Climate",       continent: "North America", remoteFriendly: false },
  { name: "Wallbox",        careersUrl: "https://wallbox.com/en_us/careers",                 industry: "Climate",       continent: "Europe",        remoteFriendly: false },
  { name: "Octopus Energy", careersUrl: "https://octopus.energy/careers",                    industry: "Climate",       continent: "Europe",        remoteFriendly: false },
  { name: "Bulb",           careersUrl: "https://bulb.co.uk/jobs",                           industry: "Climate",       continent: "Europe",        remoteFriendly: false },
  { name: "Ovo Energy",     careersUrl: "https://www.ovoenergy.com/careers",                 industry: "Climate",       continent: "Europe",        remoteFriendly: false },
  { name: "Ecotricity",     careersUrl: "https://www.ecotricity.co.uk/about-ecotricity/jobs", industry: "Climate",      continent: "Europe",        remoteFriendly: false },
  { name: "Ørsted",         careersUrl: "https://orsted.com/en/careers",                     industry: "Climate",       continent: "Europe",        remoteFriendly: false },
  { name: "Vestas",         careersUrl: "https://www.vestas.com/en/careers",                 industry: "Climate",       continent: "Europe",        remoteFriendly: false },
  { name: "Orion Energy",   careersUrl: "https://orionenergysystems.com/careers",            industry: "Climate",       continent: "North America", remoteFriendly: false },
  { name: "Inari Agriculture", careersUrl: "https://www.inari.com/careers",                  industry: "Climate",       continent: "North America", remoteFriendly: false },
  { name: "Pivot Bio",      careersUrl: "https://www.pivotbio.com/careers",                  industry: "Climate",       continent: "North America", remoteFriendly: false },
  { name: "Indigo Ag",      careersUrl: "https://www.indigoag.com/careers",                  industry: "Climate",       continent: "North America", remoteFriendly: false },
  { name: "Farmers Business Network", careersUrl: "https://www.fbn.com/careers",             industry: "Climate",       continent: "North America", remoteFriendly: true  },
  { name: "Apeel Sciences", careersUrl: "https://www.apeel.com/careers",                     industry: "Climate",       continent: "North America", remoteFriendly: false },
  { name: "NotCo",          careersUrl: "https://notco.com/careers",                         industry: "Climate",       continent: "Latin America", remoteFriendly: false },
  { name: "Oatly",          careersUrl: "https://www.oatly.com/en/stuff-we-do/jobs",         industry: "Climate",       continent: "Europe",        remoteFriendly: false },
  { name: "Better Meat Co", careersUrl: "https://bettermeat.co/careers",                     industry: "Climate",       continent: "North America", remoteFriendly: false },
  { name: "Impossible Foods", careersUrl: "https://jobs.lever.co/impossiblefoods",           industry: "Climate",       continent: "North America", remoteFriendly: false },
  { name: "Beyond Meat",    careersUrl: "https://www.beyondmeat.com/en-US/careers",          industry: "Climate",       continent: "North America", remoteFriendly: false },
  { name: "Good Food Institute", careersUrl: "https://gfi.org/careers",                      industry: "Climate",       continent: "North America", remoteFriendly: true  },
];

async function main() {
  const targetTelegramId = process.env.OWNER_TELEGRAM_ID
    ? BigInt(process.env.OWNER_TELEGRAM_ID)
    : null;

  const user = targetTelegramId
    ? await prisma.user.findUnique({ where: { telegramId: targetTelegramId } })
    : await prisma.user.findFirst({ orderBy: { createdAt: "asc" } });

  if (!user) {
    console.error("No user found in DB. Sign in to the app first, then re-run.");
    process.exit(1);
  }

  console.log(`Seeding companies for user: ${user.name ?? user.email ?? user.id}\n`);

  const countByIndustry: Record<string, number> = {};
  let imported = 0;
  let skipped = 0;

  for (const row of COMPANIES) {
    const { atsType, atsToken } = detectATS(row.careersUrl);

    try {
      await prisma.followedCompany.upsert({
        where: { userId_name: { userId: user.id, name: row.name } },
        update: {
          atsType,
          atsToken,
          careersUrl:     row.careersUrl,
          industry:       row.industry,
          continent:      row.continent,
          remoteFriendly: row.remoteFriendly,
          desiredRoles:   "product designer",
        },
        create: {
          userId:         user.id,
          name:           row.name,
          atsType,
          atsToken,
          careersUrl:     row.careersUrl,
          industry:       row.industry,
          continent:      row.continent,
          remoteFriendly: row.remoteFriendly,
          desiredRoles:   "product designer",
        },
      });
      countByIndustry[row.industry] = (countByIndustry[row.industry] ?? 0) + 1;
      imported++;
    } catch (err: any) {
      console.log(`  ⚠️  ${row.name} — skipped: ${err.message}`);
      skipped++;
    }
  }

  console.log("Companies seeded by industry:");
  for (const [industry, count] of Object.entries(countByIndustry).sort()) {
    console.log(`  ${industry.padEnd(20)} ${count}`);
  }
  console.log(`\nTotal: ${imported} upserted, ${skipped} skipped.`);

  await prisma.$disconnect();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
